name: CI
on: [push, pull_request]
jobs:
  build-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Build Docusaurus docs
        run: |
          cd website && npm install
          npm run build
