name: Lint

on:
  pull_request:
    branches: [master, main]
  merge_group:

concurrency:
  group: ci-${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  markdown-lint:
    name: markdown-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      # lint only changed files
      - uses: tj-actions/changed-files@v46
        id: changed-files
        with:
          files: "**/*.md"
          separator: ","
      - uses: DavidAnson/markdownlint-cli2-action@v19
        if: steps.changed-files.outputs.any_changed == 'true'
        with:
          config: .markdownlint.json
          globs: |
            ${{ steps.changed-files.outputs.all_changed_files }}
          separator: ","

  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: "yes"
          #        use-verbose-mode: 'yes'
          config-file: "website/mlc_config.json"
          folder-path: "specs"
